name: CI/CD Build, Test & Deploy

# DÉCLENCHEURS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Permet le déclenchement manuel

env:
  JAVA_VERSION: '17'

jobs:
  # JOB 1: TESTS
  test:
    name: Tests Maven
    runs-on: ubuntu-latest # Le job s'exécute sur une machine Ubuntu fournie par GitHub

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: maven # Cache automatique du repo Maven pour accélérer les futurs lancements

      - name: Exécution des tests
        run: mvn test -B --no-transfer-progress